### ISSUE TITLE
C++ style for enum classes is missing

### ISSUE THREAD

**Issue by rggjan** [google/styleguide#143]
The style guide doesn't mention how to label enum classes:
http://www.cprogramming.com/c++11/c++11-nullptr-strongly-typed-enum-class.html

**Comment by geoffromer** [comment]
What do you mean by how to label them?

**Comment by rggjan** [comment]
Sorry for being unclear, with "label" I mean the naming rules:

http://google.github.io/styleguide/cppguide.html#Enumerator_Names

I think for class enums that are always used with a namespace, it might make sense to not name them anymore like constants or macros.

**AlternateUrlTableErrors::MALFORMED_INPUT** looks quite strange to me...

**Comment by geoffromer** [comment]
We've discussed this a few times. For the time being, we've decided to leave the rule as it is, with the same rules for scoped and legacy enums.

**Comment by rggjan** [comment]
Ok, thats fine. But maybe this should be mentioned in the guide, though?

**Comment by geoffromer** [comment]
I don't see why. The style rule is already pretty clear that it applies to all enumerators.

**Comment by rggjan** [comment]
It wasn't clear to me, otherwise I wouldn't have asked ;)
Just thought it wouldn't hurt to make it explicit by adding "enum (scoped and unscoped)" to the text, or by adding an example with an "enum class" enumerator...

**Comment by geoffromer** [comment]
OK, I've added a clarification to our internal copy of the style guide. It will become visible on GitHub the next time we do a push.

**Comment by rggjan** [comment]
Great, thanks :)

**Comment by bkramer-moz** [comment]
For my two cents, enum class forces qualification so that you shouldn't need the "hungarian notation" of 'k'. 

I am guessing the history of this guideline started with the observation that constant declarations such as `const int x = 1;` demanded clarity by changing to `const int kX = 1;` and unscoped enums are semantically equivalent to `const int` (or whatever the chosen base integer type is).  I wonder what the argument was to apply the same style to scoped enums?  

Also think of this way: I have a class `X { void foo(); }`.  'foo' is a constant too: its type is `const (*)()`. You can get the value (the function address), but you can't assign to it.  So why not require `class X {void kFoo(); }`?

We should remember _why_ we use the `k`. It's supposed to be a way to more easily tell when a primitive value is assignable versus not, and I think with `class enum` it's already obvious.

**Comment by hploeb** [comment]
@bkramer-moz I totally agree with that, the `k` naming for scoped enum classes is pointless.

**Comment by geoffromer** [comment]
@bkramer-moz The purpose of a naming convention like this is to make information clear at the point where the name is used, not necessarily at the point where it's defined. In a usage like `Foo::bar`, it's not obvious that `bar` is immutable, because it's not obvious that `Foo` is an enum.
