### ISSUE TITLE
htmlcssguide error : no comments above doctpye

### ISSUE THREAD

**Issue by ronnievsmith** [google/styleguide#152]
Under HTML Validity it says:

```
<!-- Recommended -->
<!DOCTYPE html>
<meta charset="utf-8">
<title>Test</title>
<article>This is only a test.</article>
```

However, W3C validator says nothing should go above the doctype declaration, not even a comment.

**Comment by seastarrrr** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Test</title>
</head>
<body>
  <article>This is only a test.</article>
</body>
</html>

**Comment by seastarrrr** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Test</title>
</head>
<body>
  <article>This is only a test.</article>
</body>
</html>

**Comment by seastarrrr** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Test</title>
</head>
<body>
  <article>This is only a test.</article>
</body>
</html>

**Comment by trottiemcqueen** [comment]
I would like to help

**Comment by vapier** [comment]
the `<!-- Recommended -->` isn't meant to be copied over literally.  if you look at all the code snippets, they have a comment at the top to show whether the snippet is/isn't recommended.  imo it's kind of obvious that the comment shouldn't be retained literally when you see that every example is written this way.

arguably they aren't needed in any of the examples due to the coloring, but it helps with people who can't see the colors.

i'm inclined to leave it as-is.
