### ISSUE TITLE
WHY NO PHP?

### ISSUE THREAD

**Issue by xuanskyer** [google/styleguide#203]
WHY NO PHP?

**Comment by tituswinters** [comment]
Because style guides are a way to enforce engineering policy and guide people to best practices, not just a vehicle for arbitrary rules.  (I gave a talk on our approach to style guides a couple years back: https://www.youtube.com/watch?v=NOCElcMcFik) 

I suppose you can read that either as "We don't generally use PHP, so we don't have policy to share on that" or "Best practices suggest you don't use PHP."  Take your pick. :P
