### ISSUE TITLE
Disallowing copy/move in the public: section in C++

### ISSUE THREAD

**Issue by sjincho** [google/styleguide#255]
In the [Copyable and Movable Types section of the C++ guide](https://google.github.io/styleguide/cppguide.html#Copyable_Movable_Types) it says that we should delete the methods in the `public:` section.

But as far as I remember, we used to delete them in the `private:` section.

From: https://chromium.googlesource.com/chromium/src/base/+/master/macros.h#23
```
// A macro to disallow the copy constructor and operator= functions.
// This should be used in the private: declarations for a class.
#define DISALLOW_COPY_AND_ASSIGN(TypeName) \
  TypeName(const TypeName&) = delete;      \
  void operator=(const TypeName&) = delete
```

Can you share any reason for the change?

**Comment by tituswinters** [comment]
It used to be in the private section because DISALLOW_COPY_AND_ASSIGN was a hack relying on declaring the copy c'tor and assignment operator private (and then not defining them).  

C++11 provides us =delete as a first-class way of saying those special members are suppressed, so the mechanics of "make it private" are not necessary.

Given that there's no longer a technical reason, the question becomes "Which is clearer, stylistically?" We believe that the copyability of a type is a rather important property, and should be clearly stated to the reader.  Putting that information in the public section (rather than hidden away in the implementation details of the private section) gives the right information to users of the type.

**Comment by chrisandrewca** [comment]
@tituswinters 

Hey tituswinters, thanks for your insight. If... you have the time... would you entertain my curiosity?

I'm wondering... in which cases does the semantic meaning of the copyability of an object require that information to be in the public section of a class (less technical/syntatical reasons if I'm completely off base)?

**Comment by tituswinters** [comment]
If C++ were a language with higher-level design, the first-order things you'd want to know about a type, in general, would be "Is this regular/a value, is this move-only (semi-regular), or is this something else?" The other methods and stuff are of course important, but understanding the basic affordances helps characterize how it's intended to be used. 

We don't really want to encourage people digging around in the private: section just to know what the type *is*. Hence "put it in the public section." This could also be done with comments, but that leaves open the chance for it to fall out of sync ... it just seems simplest/cleanest to put these details right up front in a technical (and enforced) fashion.

**Comment by chrisandrewca** [comment]
Got it - thanks for your insight. Is that was is generally called a "convention"?

**Comment by tituswinters** [comment]
"Style guidance and best practice that isn't enforced by language rules" seems like a reasonable definition of "convention," yes.
