### ISSUE TITLE
Python style guide mingles class attributes with instance attributes

### ISSUE THREAD

**Issue by alanfranz** [google/styleguide#263]
When explaining how to comment classes

https://github.com/google/styleguide/blob/gh-pages/pyguide.html#L1668

the guide says:

```If your class has public attributes, they should be documented here in an Attributes section and follow the same formatting as a function's Args section.```

but the attributes in the example are actually public **instance** attributes, not class attributes, as both can exist and coexist in Python.

It seems that the guide was directed towards **instance** attributes, hence the doc should be corrected (and I wouldn't know how to comment class attributes, beyond the possible inline comment).

**Comment by gpshead** [comment]
this text is still present in our modern python style guide https://github.com/google/styleguide/blob/gh-pages/pyguide.md#384-classes

We don't explicitly specify what kind of attributes here because from an object API user standpoint, it should not matter if they happen to be class or instance.  It's all `thing.attribute_name` to them.

**Comment by alanfranz** [comment]
From an API standpoint, if you've got an instance, it does not matter whether the attribute is on the instance or the class; but, if I have got a **class**, that object might not expose instance attributes.

@gpshead so the docs are for documenting **instance** attributes, as I said, not class attributes. Of course it's entirely OK if you choose not to document class-only attributes.
