### ISSUE TITLE
HTML/CSS Style Guide: css color keywords recommended or not?

### ISSUE THREAD

**Issue by gemwuu** [google/styleguide#361]
According to [W3 docs](https://www.w3.org/TR/2018/PR-css-color-3-20180315/#html4), we can, at least, use 17 basic css color keywords. Are there any pros or cons using these keywords in CSS code?

**Comment by tonyruscoe** [comment]
Hi gemwuu. Apologies for the delay in responding to this!

Our recommendation is to use 3-character hexadecimal notation where possible, though we don’t specify what to use when that isn’t possible:

https://google.github.io/styleguide/htmlcssguide.html#Hexadecimal_Notation

There’s no problem with using color keywords, but I’d suggest being consistent across your project instead of using color keywords where possible and hexadecimal or RGB color values elsewhere.
