### ISSUE TITLE
Can it be translated into other languages?

### ISSUE THREAD

**Issue by raoyi** [google/styleguide#458]
we need other languages' version, such as chinese, japanese etc. or you can get pull requests for this from others.

**Comment by Akshat162001** [comment]
https://github.com/KandulaDinesh/Lanaguge_Translation 
Try this u will get solution to the problem. Hopefully..

**Comment by vapier** [comment]
tbh, I don't see this happening.  (American) English is required inside of Google for all technical work, and we don't translate any of it internally.  writing documentation for the purpose of translating is difficult & time consuming, and requires a lot of back & forth with translators, as well as extended annotations, to make sure ideas are conveyed correctly.

it would be a great public service imo, but since Google would gain nothing (internally) for it, and would add significant overhead for everyone involved, it's pretty much a non-starter.
