### ISSUE TITLE
Why is #pragma once discouraged?

### ISSUE THREAD

**Issue by ernestum** [google/styleguide#538]
I could not find any justification for this in the C++ style guide.

**Comment by markmentovai** [comment]
Compilers detect the pattern `#ifndef X`/`#define X`/`#endif  // X` wrapped around an entire file, and optimize this into, essentially, `#pragma once`. The `#if`-based variant is standard, and necessary for correct standard-conformant compilation, so we require it for all headers that must be `#include`d only once (the vast majority of headers). Because the `#pragma` is both non-standard and redundant, we prohibit it.
