### ISSUE TITLE
C++: switch statements should always have a default case, but what about if and else?

### ISSUE THREAD

**Issue by john-cj** [google/styleguide#556]
https://google.github.io/styleguide/cppguide.html#Loops_and_Switch_Statements

> If not conditional on an enumerated value, **`switch` statements should always have a default case**.

For what reason this guideline exists for `switch` only, and not for `if`?

```
if (condition1) {
  ...
} else if (condition2) {
  ...
} else {
  assert(false);
}
```

**Comment by tituswinters** [comment]
Only because of convention. It's common/conventional to see a `switch` over an `enum` that is attempting to do one of N things: a reader will commonly assume such a switch *is* exhaustive, without necessarily checking the mapping. (This is why there is commonly a warning in some compilers for this.)

For if/else sequences, that is less conventional, and thus less likely to mislead. I agree that there is no technical semantic distinction that should treat the two differently. 

(Honestly, this section probably doesn't pull its weight: this is behavior that is better enforced by compiler warnings and static analysis: humans shouldn't bother with it when tools will do a better job.)

Does that help?

**Comment by john-cj** [comment]
Yes, it completely answers my question. Thanks :+1:
