### ISSUE TITLE
Python Style Guide is missing section 3.9 (guidance for classes)

### ISSUE THREAD

**Issue by brian-c-ogorman** [google/styleguide#627]
The Python Style Guide is missing section 3.9, which previously had style rules for classes. The table of contents also jumps from section 3.8 to 3.10.

**Comment by gpshead** [comment]
This is intentional.  We removed sections 2.15 (deprecated language features) and 3.9 (classes) last ~October as they were Python 2 focused.

2.15 talked about the `string` module from 1.5.2 :P

3.9 basically just said _"Classes need not explicitly inherit from `object` (unless for compatibility with
Python 2)."_

We don't renumber when sections are removed as there are numeric anchor tags (at least internally) that things have chosen to link to for better or worse over the yearsso we try to keep those alive.  It does make for an amusing table of contents.

**Comment by brian-c-ogorman** [comment]
I see. Thanks for the clarification!
