### ISSUE TITLE
Python class style guide goes against PEP-257

### ISSUE THREAD

**Issue by Tecktron** [google/styleguide#628]
[Style Guide](https://google.github.io/styleguide/pyguide.html#384-classes)

>If your class has public attributes, they should be documented here in an Attributes section and follow the same formatting as a function’s Args section.

[PEP-257](https://www.python.org/dev/peps/pep-0257/):

>The docstring for a class should summarize its behavior and list the public methods and instance variables. If the class is intended to be subclassed, and has an additional interface for subclasses, this interface should be listed separately (in the docstring). The class constructor should be documented in the docstring for its init method. Individual methods should be documented by their own docstring.

PEP clearly states that attributes for a class's `__init__` function should live within the init function itself and not at the class level which should be left for subclassing interfaces. 

Having attributes at the class level may also add confusion for classes that implement interfaces as well as a `__call__` method.

I'm at least curious as to why the deviation from the PEP here?

**Comment by Tecktron** [comment]
As found in https://github.com/google/styleguide/issues/575 , this also adds more confusion

**Comment by gpshead** [comment]
I don't see a conflict with PEP-257.  

```
class Klass:
    """$docstring."""
```

We want the class `$docstring` to describe the API of the class including the public attributes.  So that people using the class have a good feel for what they need to know from the class docstring alone.  A class constructor `__init__` docstring should just describe what its arguments are, and, if it calls any logic itself, what it does.  This can lead to duplication between the class docstring and `__init__` docstring at times as the description parameters for `__init__` and public attributes are _often_ but not always the same.  If someone wants to make one of those two more brief in that situation, I recommend the `__init__` docstring Args: descriptions be the brief ones, referring to the class docstring.

As for `__call__`, that should be documented on the `__call__` method itself. A class docstring _might_ choose to mention that instances are callable and go into an example of how that is intended to be used.

I'm closing this issue as we're not likely to change our advice here unless this comes up with a compelling reason internally.

**Comment by Tecktron** [comment]
So your "standards" are lacking thoughtfulness, contain logical holes and increase repetition. Got it.  I guess you can admit that and that l you're too lazy to improve it. Typical. Can't say I expect anything else.

**Comment by Tecktron** [comment]
So your "standards" are lacking thoughtfulness, contain logical holes and increase repetition. Got it.  I guess you can at least admit that and acknowledge you're too lazy to actually improve it. Typical. Can't say I really expected anything else.

**Comment by fischbacher** [comment]
I'd like to provide some clarification.

On: 

"PEP clearly states that attributes for a class's __init__ function should live within the init function itself and not at the class level which should be left for subclassing interfaces."

There is no such a thing as "attributes for a class's __init__ function". 
The relevant terms for discussing this issue are:

https://docs.python.org/3/glossary.html#term-argument
https://docs.python.org/3/glossary.html#term-parameter
https://docs.python.org/3/glossary.html#term-attribute

An __init__ function definition has parameters.
A call to __init__ (as it occurs when instantiating the class) has arguments. The class instance has attributes.

Let us consider this common situation:

class Foo:
  """{...Summary of what the instance represents...}

  Attributes:
    name: The name with which this instance self-identifies. Must not be assigned to.
  """

  def __init__(self, *, name='abc', caching=False):
     """Initializes the instance.

      Args:
         name: str, Name with which this instance identifies itself.
         caching: bool, whether to use caching.
      """
      super().__init__()  # For not breaking MRO in multiple-inheritance situations.
      self.name = name
      self._use_caching = caching

The __init__ method definition has two parameters, both optional (forced-)keyword arguments. One of these parameters then sets a public(-by-naming-convention) attribute on the instance, while the other one sets a private(-by-naming-convention) attribute. The class docstring documents the public attributes (only one here) - here then also with extra details on attribute usage expectations (which would not make sense for a parameter). In this case, one class attribute closely corresponds to an __init__ parameter, but there is a difference between the attribute and the parameter, and both need to be documented.


Now, a common situation is that some class mostly has attributes that are taken straight from __init__ parameters.

Here, the usual approach is to decorate the class as a @dataclasses.dataclass (ideally, "frozen=True") and have __init__ synthesized from the information in class.__annotations__. In that case, the class being a @dataclasses.dataclass generated class plus the class-docstring, which documents the attributes, completely specify the behavior of the synthesized __init__.
