### ISSUE TITLE
C++ "Inputs and Outputs" section improvement

### ISSUE THREAD

**Issue by d-uspenskiy** [google/styleguide#712]
The "Inputs and Outputs" section contains the following text

> Avoid defining functions that require a const reference parameter to outlive the call, because const reference parameters bind to temporaries. Instead, find a way to eliminate the lifetime requirement (for example, by copying the parameter), or pass it by const pointer and document the lifetime and non-null requirements.

Using of const pointer is not the best option in such situation. `std::reference_wrapper<const T>` could be used instead.

```
struct Filter {
    bool operator()(int value) const {
...
    }
};

struct Handler {
    explicit Handler(const Filter& filter) : filter_(filter) {}

    void operator()(int value) {
        if (filter_(value)) {
...
        }
    }

    const Filter& filter_;
};

...
Filter filter;
Handler handler{filter};
handler(10); // OK
...
Handler handler{Filter()};
handler(10); // Undefined behavior
...
```

Using of `std::reference_wrapper` in Filter's constructor makes second situation impossible

```
explicit Handler(std::reference_wrapper<const Filter> filter) : filter_(filter) {}
```

**Comment by acharyasourav** [comment]
Hey @d-uspenskiy can you please elaborate what needs to be done. I would like to give this a try.

**Comment by tituswinters** [comment]
I *absolutely* disapprove of use of `reference_wrapper` for that purpose. Just because it appears in the standard doesn't mean it's useful, and *in particular* that class template is only designed to be useful in exotic contexts. It's useful for generic code that needs to support references in an almost-regular fashion (rare). It has so much special case handling (in CTAD, in structured bindings, etc) and is so full of edge cases ... it's *really* not a good habit to use. 

Yes, technically you can solve that problem in that fashion, but in my professional opinion that's a solution that's far worse than the problem.

**Comment by d-uspenskiy** [comment]
Actually the idea is to use some helper wrapper class which can't be build from rvalue reference.

so instead of code like
```
const std::string& func(const std::string& arg) {
  ...
  return arg;
}
```

the following code could be used to avoid tmp object reference problem

```
const std::string& func(NonTmpObjRef<const std::string> arg) {
  ...
  return arg;
}
```

But instead of introducing hand made `std::reference_wrapper` could be used because it does exactly what is needed.

I agree that the `std::reference_wrapper` type name name is non self descriptive in particular context.
But it is possible to create an alias

```
template <class T>
using NonTmpObjRef = std::reference_wrapper<T>;

const std::string& func(NonTmpObjRef<const std::string> arg) {
  ...
  return arg;
}

```

or even 

```
template <class T>
using NonTmpObjRef = std::reference_wrapper<const T>;

const std::string& func(NonTmpObjRef<std::string> arg) {
  ...
  return arg;
}
```

to avoid unnecessary `const`
