### ISSUE TITLE
Why output parameters be sugguested as reference rather than pointer

### ISSUE THREAD

**Issue by yexinhua1998** [google/styleguide#803]
Google c++ style sugguest output parameter as pointer before.  But after [this commit](https://github.com/google/styleguide/commit/7a7a2f510efe7d7fc5ea8fbed549ddb31fac8f3e#diff-26120df7bca3279afbf749017c778545), this suggestion is changed and output parameters is suggested as reference. I am confused about why do this chagne and what problem you meet in practice and what benefit with new rule.
Thanks for answer!

**Comment by vapier** [comment]
i don't have the references off the top of my head, but iirc, this is to move away from raw pointers and to things like [std::optional](https://en.cppreference.com/w/cpp/utility/optional) (new in C++17) to mitigate common errors like dereferencing NULL pointers.

considering how long the pointer guidance has been around, the style guide is taking a bit of a transitional approach.  you can see how it talked about `absl::optional` at the time, but has since been updated to only mention `std::optional`.
