### ISSUE TITLE
shell style linter

### ISSUE THREAD

**Issue by aleksandr-vin** [google/styleguide#93]
Is there a plan to add linter for checking shell style?

**Comment by mvdan** [comment]
Take a look at https://github.com/mvdan/sh#shfmt - in particular, `shfmt -i 2 -ci` can modify your scripts to follow the format bits of the shell style guide. For example, indentation and spacing of operators.

**Comment by IsaacG** [comment]
The [Shell Style Guide](https://google.github.io/styleguide/shellguide.html#s6.1-shellcheck) now points to [ShellCheck](https://www.shellcheck.net/). That project provides a linter.

**Comment by sztomi** [comment]
Shellcheck does not seem to check most recommendations in the style guide. I think the linked passage in the guide does not imply that it is meant to be a linter for the guide itself.

**Comment by vapier** [comment]
i think the status quo is fine here.  the guide says to use shellcheck as it'll catch a lot of common issues.  it doesn't say passing the linter is equiv to passing the style guide.  i don't see us trying to extend shellcheck here -- not many people want to write Haskell ;).

would be nice if we could integrate shfmt for more of the formatting decisions rather than correctness/linting aspects.
